# Generated by Django 2.1.5 on 2019-06-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('participants', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('thumb', models.CharField(blank=True, max_length=500)),
                ('key', models.CharField(max_length=20)),
            ],
        ),
    ]
