# Generated by Django 2.1.5 on 2019-06-15 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bored_api', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boreduser',
            name='last_activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bored_api.Activity'),
        ),
    ]
