# Generated by Django 2.1.5 on 2019-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bored_api', '0003_auto_20190615_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
