# Generated by Django 2.1.5 on 2019-06-16 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bored_api', '0007_auto_20190616_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boreduser',
            name='last_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bored_api.Activity'),
        ),
    ]
