# Generated by Django 2.1.5 on 2019-06-16 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bored_api', '0008_auto_20190616_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boreduser',
            name='last_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_activity', to='bored_api.Activity'),
        ),
        migrations.RemoveField(
            model_name='boreduser',
            name='saved_activities',
        ),
        migrations.AddField(
            model_name='boreduser',
            name='saved_activities',
            field=models.ManyToManyField(blank=True, related_name='saved_activities', to='bored_api.Activity'),
        ),
    ]
